# Generated by Django 6.0.5 on 2026-05-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100, unique=True, verbose_name='Internal ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Name')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('preco', models.FloatField(verbose_name='Price')),
                ('moeda', models.CharField(default='USD', max_length=10, verbose_name='Currency')),
                ('estoque', models.IntegerField(default=0, verbose_name='Stock')),
                ('ean', models.CharField(blank=True, max_length=50, null=True, verbose_name='EAN')),
                ('cor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size')),
                ('disponibilidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Availability')),
            ],
        ),
    ]
